name: Pull Request

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: QA
    secrets: inherit
    uses: ./.github/workflows/_qa.yml
